//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENDAMENTO()
        {
            this.MATERIAL_AGENDAMENTO = new HashSet<MATERIAL_AGENDAMENTO>();
        }
    
        public int ID_AGENDAMENTO { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_PONTO { get; set; }
        public System.DateTime DATA_HORA { get; set; }
        public Nullable<int> QUANTIDADE_TOTAL { get; set; }
    
        public virtual PONTO_COLETA PONTO_COLETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_AGENDAMENTO> MATERIAL_AGENDAMENTO { get; set; }
    }
}
