//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models {
    using RecycleBitBackEnd.Config;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextEntities : DbContext {
        public ContextEntities()
             : base("metadata=res://*/;provider=System.Data.SqlClient;provider connection string=';data source=" + ApplicationConfig.SQL_INSTANCE_NAME + ";initial catalog=" + ApplicationConfig.SQL_DB_NAME + ";uid=" + ApplicationConfig.SQL_USER + ";pwd=" + ApplicationConfig.SQL_USER_PASSWORD + ";MultipleActiveResultSets=True;App=EntityFramework'") {
        }
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENDAMENTO> AGENDAMENTO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ENDERECO> ENDERECO { get; set; }
        public virtual DbSet<MATERIAL> MATERIAL { get; set; }
        public virtual DbSet<MATERIAL_AGENDAMENTO> MATERIAL_AGENDAMENTO { get; set; }
        public virtual DbSet<MATERIAL_PONTO_COLETA> MATERIAL_PONTO_COLETA { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PONTO_COLETA> PONTO_COLETA { get; set; }
        public virtual DbSet<PUBLICACAO> PUBLICACAO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_AUDIT> USUARIO_AUDIT { get; set; }
        public virtual DbSet<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
    }
}
