//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_PONTO_COLETA
    {
        public int ID_MATERIAL_PONTO_COLETA { get; set; }
        public int ID_PONTO { get; set; }
        public int ID_MATERIAL { get; set; }
        public Nullable<int> QUANTIDADE_ESTIMADA { get; set; }
    
        public virtual MATERIAL MATERIAL { get; set; }
        public virtual PONTO_COLETA PONTO_COLETA { get; set; }
    }
}
