//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIAL()
        {
            this.MATERIAL_PONTO_COLETA = new HashSet<MATERIAL_PONTO_COLETA>();
            this.MATERIAL_AGENDAMENTO = new HashSet<MATERIAL_AGENDAMENTO>();
        }
    
        public int ID_MATERIAL { get; set; }
        public bool STATUS { get; set; }
        public string NOME_MATERIAL { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> NIVEL_PERICULOSIDADE { get; set; }
        public Nullable<bool> REQUER_TRANSPORTE_ESPECIAL { get; set; }
        public string INSTRUCAO_MANUSEIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_PONTO_COLETA> MATERIAL_PONTO_COLETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_AGENDAMENTO> MATERIAL_AGENDAMENTO { get; set; }
    }
}
