//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_AGENDAMENTO
    {
        public int ID_MATERIAL_AGENDAMENTO { get; set; }
        public int ID_MATERIAL { get; set; }
        public int ID_AGENDAMENTO { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
    
        public virtual AGENDAMENTO AGENDAMENTO { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
