//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PONTO_COLETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PONTO_COLETA()
        {
            this.AGENDAMENTO = new HashSet<AGENDAMENTO>();
            this.MATERIAL_PONTO_COLETA = new HashSet<MATERIAL_PONTO_COLETA>();
            this.PUBLICACAO = new HashSet<PUBLICACAO>();
        }
    
        public int ID_PONTO { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public int ID_ENDERECO { get; set; }
        public string ID_EMPRESA { get; set; }
        public Nullable<int> NIVEL_MAX_PERICULOSIDADE { get; set; }
        public bool STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDAMENTO> AGENDAMENTO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ENDERECO ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_PONTO_COLETA> MATERIAL_PONTO_COLETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICACAO> PUBLICACAO { get; set; }
    }
}
