//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACAO
    {
        public int ID_PUBLICACAO { get; set; }
        public int ID_PONTO { get; set; }
        public string IMAGEM { get; set; }
        public bool STATUS { get; set; }
        public string DESCRICAO { get; set; }
        public string TITULO { get; set; }
        public Nullable<System.DateTime> DATA_HORA { get; set; }
    
        public virtual PONTO_COLETA PONTO_COLETA { get; set; }
    }
}
