//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PERFIL
    {
        public int ID_USUARIO_PERFIL { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_PERFIL { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
