//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.AGENDAMENTO = new HashSet<AGENDAMENTO>();
            this.USUARIO_PERFIL = new HashSet<USUARIO_PERFIL>();
        }
    
        public int ID_USUARIO { get; set; }
        public int ID_ENDERECO { get; set; }
        public string CPF { get; set; }
        public bool STATUS { get; set; }
        public string NOME { get; set; }
        public string SENHA { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public string PERFIL { get; set; }
        public System.DateTime NASCIMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDAMENTO> AGENDAMENTO { get; set; }
        public virtual ENDERECO ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
    }
}
