//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPIRailwayWeightingBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_AUDIT
    {
        public int AUDIT_ID { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string OPERACAO { get; set; }
        public Nullable<System.DateTime> DATA_HORA { get; set; }
        public string DADOS { get; set; }
    }
}
