//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.MrsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pesagem", Namespace="http://schemas.datacontract.org/2004/07/WCFIntegracaoPesagens.Modelo")]
    [System.SerializableAttribute()]
    public partial class Pesagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RecycleBitBackEnd.MrsService.Eixo[] EixosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RecycleBitBackEnd.MrsService.Veiculo[] ListaVeiculosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixoField;
        
        private string TipoBalancaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RecycleBitBackEnd.MrsService.Eixo[] Eixos {
            get {
                return this.EixosField;
            }
            set {
                if ((object.ReferenceEquals(this.EixosField, value) != true)) {
                    this.EixosField = value;
                    this.RaisePropertyChanged("Eixos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RecycleBitBackEnd.MrsService.Veiculo[] ListaVeiculos {
            get {
                return this.ListaVeiculosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaVeiculosField, value) != true)) {
                    this.ListaVeiculosField = value;
                    this.RaisePropertyChanged("ListaVeiculos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefixo {
            get {
                return this.PrefixoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixoField, value) != true)) {
                    this.PrefixoField = value;
                    this.RaisePropertyChanged("Prefixo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TipoBalanca {
            get {
                return this.TipoBalancaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoBalancaField, value) != true)) {
                    this.TipoBalancaField = value;
                    this.RaisePropertyChanged("TipoBalanca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Eixo", Namespace="http://schemas.datacontract.org/2004/07/WCFIntegracaoPesagens.Modelo")]
    [System.SerializableAttribute()]
    public partial class Eixo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime Datak__BackingFieldField;
        
        private int Idk__BackingFieldField;
        
        private int NumeroEixok__BackingFieldField;
        
        private RecycleBitBackEnd.MrsService.Roda[] Rodask__BackingFieldField;
        
        private double Velocidadek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Data>k__BackingField", IsRequired=true)]
        public System.DateTime Datak__BackingField {
            get {
                return this.Datak__BackingFieldField;
            }
            set {
                if ((this.Datak__BackingFieldField.Equals(value) != true)) {
                    this.Datak__BackingFieldField = value;
                    this.RaisePropertyChanged("Datak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<NumeroEixo>k__BackingField", IsRequired=true)]
        public int NumeroEixok__BackingField {
            get {
                return this.NumeroEixok__BackingFieldField;
            }
            set {
                if ((this.NumeroEixok__BackingFieldField.Equals(value) != true)) {
                    this.NumeroEixok__BackingFieldField = value;
                    this.RaisePropertyChanged("NumeroEixok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Rodas>k__BackingField", IsRequired=true)]
        public RecycleBitBackEnd.MrsService.Roda[] Rodask__BackingField {
            get {
                return this.Rodask__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Rodask__BackingFieldField, value) != true)) {
                    this.Rodask__BackingFieldField = value;
                    this.RaisePropertyChanged("Rodask__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Velocidade>k__BackingField", IsRequired=true)]
        public double Velocidadek__BackingField {
            get {
                return this.Velocidadek__BackingFieldField;
            }
            set {
                if ((this.Velocidadek__BackingFieldField.Equals(value) != true)) {
                    this.Velocidadek__BackingFieldField = value;
                    this.RaisePropertyChanged("Velocidadek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Veiculo", Namespace="http://schemas.datacontract.org/2004/07/WCFIntegracaoPesagens.Modelo")]
    [System.SerializableAttribute()]
    public partial class Veiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DataField;
        
        private string EstadoField;
        
        private string IdentificacaoField;
        
        private RecycleBitBackEnd.MrsService.Roda[] ListaRodasField;
        
        private int NumeroVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdutoField;
        
        private string TipoVeiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Identificacao {
            get {
                return this.IdentificacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacaoField, value) != true)) {
                    this.IdentificacaoField = value;
                    this.RaisePropertyChanged("Identificacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public RecycleBitBackEnd.MrsService.Roda[] ListaRodas {
            get {
                return this.ListaRodasField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaRodasField, value) != true)) {
                    this.ListaRodasField = value;
                    this.RaisePropertyChanged("ListaRodas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroVeiculo {
            get {
                return this.NumeroVeiculoField;
            }
            set {
                if ((this.NumeroVeiculoField.Equals(value) != true)) {
                    this.NumeroVeiculoField = value;
                    this.RaisePropertyChanged("NumeroVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TipoVeiculo {
            get {
                return this.TipoVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVeiculoField, value) != true)) {
                    this.TipoVeiculoField = value;
                    this.RaisePropertyChanged("TipoVeiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roda", Namespace="http://schemas.datacontract.org/2004/07/WCFIntegracaoPesagens.Modelo")]
    [System.SerializableAttribute()]
    public partial class Roda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PesoLiquidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PesoTaraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PesoLiquido {
            get {
                return this.PesoLiquidoField;
            }
            set {
                if ((this.PesoLiquidoField.Equals(value) != true)) {
                    this.PesoLiquidoField = value;
                    this.RaisePropertyChanged("PesoLiquido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PesoTara {
            get {
                return this.PesoTaraField;
            }
            set {
                if ((this.PesoTaraField.Equals(value) != true)) {
                    this.PesoTaraField = value;
                    this.RaisePropertyChanged("PesoTara");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WCFIntegracaoPesagensExternas", ConfigurationName="MrsService.IntegracaoPesagensExternasContract")]
    public interface IntegracaoPesagensExternasContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFIntegracaoPesagensExternas/IntegracaoPesagensExternasContract/GravarPesagem", ReplyAction="WCFIntegracaoPesagensExternas/IntegracaoPesagensExternasContract/GravarPesagemRes" +
            "ponse")]
        bool GravarPesagem(RecycleBitBackEnd.MrsService.Pesagem Pesagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFIntegracaoPesagensExternas/IntegracaoPesagensExternasContract/GravarPesagem", ReplyAction="WCFIntegracaoPesagensExternas/IntegracaoPesagensExternasContract/GravarPesagemRes" +
            "ponse")]
        System.Threading.Tasks.Task<bool> GravarPesagemAsync(RecycleBitBackEnd.MrsService.Pesagem Pesagem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegracaoPesagensExternasContractChannel : RecycleBitBackEnd.MrsService.IntegracaoPesagensExternasContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracaoPesagensExternasContractClient : System.ServiceModel.ClientBase<RecycleBitBackEnd.MrsService.IntegracaoPesagensExternasContract>, RecycleBitBackEnd.MrsService.IntegracaoPesagensExternasContract {
        
        public IntegracaoPesagensExternasContractClient() {
        }
        
        public IntegracaoPesagensExternasContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracaoPesagensExternasContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoPesagensExternasContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoPesagensExternasContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GravarPesagem(RecycleBitBackEnd.MrsService.Pesagem Pesagem) {
            return base.Channel.GravarPesagem(Pesagem);
        }
        
        public System.Threading.Tasks.Task<bool> GravarPesagemAsync(RecycleBitBackEnd.MrsService.Pesagem Pesagem) {
            return base.Channel.GravarPesagemAsync(Pesagem);
        }
    }
}
