//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLECTION_POINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLLECTION_POINT()
        {
            this.MATERIAL_COLLECTION_POINT = new HashSet<MATERIAL_COLLECTION_POINT>();
            this.PUBLICATION = new HashSet<PUBLICATION>();
            this.SCHEDULE = new HashSet<SCHEDULE>();
        }
    
        public int POINT_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int ADDRESS_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public Nullable<int> MAX_HAZARD_LEVEL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_COLLECTION_POINT> MATERIAL_COLLECTION_POINT { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICATION> PUBLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULE> SCHEDULE { get; set; }
    }
}
