//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.Models {
    using RecycleBitBackEnd.Config;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class RecycleBitEntities : DbContext {
        public RecycleBitEntities()
            : base("metadata=res://*/;provider=System.Data.SqlClient;provider connection string=';data source=" + ApplicationConfig.SQL_INSTANCE_NAME + ";initial catalog=" + ApplicationConfig.SQL_DB_NAME + ";uid=" + ApplicationConfig.SQL_USER + ";pwd=" + ApplicationConfig.SQL_USER_PASSWORD + ";MultipleActiveResultSets=True;App=EntityFramework'") {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ADDRESS> ADDRESS { get; set; }
        public virtual DbSet<COLLECTION_POINT> COLLECTION_POINT { get; set; }
        public virtual DbSet<COMPANY> COMPANY { get; set; }
        public virtual DbSet<MATERIAL> MATERIAL { get; set; }
        public virtual DbSet<MATERIAL_COLLECTION_POINT> MATERIAL_COLLECTION_POINT { get; set; }
        public virtual DbSet<MATERIAL_SCHEDULE> MATERIAL_SCHEDULE { get; set; }
        public virtual DbSet<PUBLICATION> PUBLICATION { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_AUDIT> USER_AUDIT { get; set; }
    }
}
