//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_SCHEDULE
    {
        public int MATERIAL_SCHEDULE_ID { get; set; }
        public int MATERIAL_ID { get; set; }
        public int SCHEDULE_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual MATERIAL MATERIAL { get; set; }
        public virtual SCHEDULE SCHEDULE { get; set; }
    }
}
