//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIAL()
        {
            this.MATERIAL_COLLECTION_POINT = new HashSet<MATERIAL_COLLECTION_POINT>();
            this.MATERIAL_SCHEDULE = new HashSet<MATERIAL_SCHEDULE>();
        }
    
        public int MATERIAL_ID { get; set; }
        public bool STATUS { get; set; }
        public string MATERIAL_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> HAZARD_LEVEL { get; set; }
        public Nullable<bool> REQUIRES_SPECIAL_TRANSPORT { get; set; }
        public string HANDLING_INSTRUCTIONS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_COLLECTION_POINT> MATERIAL_COLLECTION_POINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_SCHEDULE> MATERIAL_SCHEDULE { get; set; }
    }
}
