//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICATION
    {
        public int PUBLICATION_ID { get; set; }
        public int POINT_ID { get; set; }
        public string IMAGE_PUBLICATION_PATH { get; set; }
        public bool STATUS { get; set; }
        public string DESCRIPTION { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
    
        public virtual COLLECTION_POINT COLLECTION_POINT { get; set; }
    }
}
