//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCHEDULE()
        {
            this.MATERIAL_SCHEDULE = new HashSet<MATERIAL_SCHEDULE>();
        }
    
        public int SCHEDULE_ID { get; set; }
        public int USER_ID { get; set; }
        public int POINT_ID { get; set; }
        public System.DateTime DATE_TIME { get; set; }
        public Nullable<int> TOTAL_QUANTITY { get; set; }
    
        public virtual COLLECTION_POINT COLLECTION_POINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_SCHEDULE> MATERIAL_SCHEDULE { get; set; }
        public virtual USER USER { get; set; }
    }
}
