//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleBitBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_AUDIT
    {
        public int AUDIT_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string OPERATION { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public string DATA { get; set; }
    }
}
