/*==============================================================*/
/* Table: DUAPT_QUEUE_STATUS                                    */
/*==============================================================*/

CREATE TABLE [BDVPIPESAGEM].[DUAPT_QUEUE_STATUS](
	[DUAP_QUEUE_STATUS_ID] [int] IDENTITY(1,1) NOT NULL,
	[DUAP_DATETIME] [datetime] NOT NULL,
	[DUAP_STATUS] [varchar](15) NOT NULL,
	[DUAP_STATUS_DESCRIPTION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_BDVPIPESAGEM.DUAP_QUEUE_STATUS] PRIMARY KEY CLUSTERED 
(
	[DUAP_QUEUE_STATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

grant INSERT,DELETE,UPDATE on [BDVPIPESAGEM].[DUAPT_QUEUE_STATUS] to AVPIPESAGEM
go

grant SELECT on [BDVPIPESAGEM].[DUAPT_QUEUE_STATUS] to CVPIPESAGEM
go


/*==============================================================*/
/* Table: DUAOT_WEIGHING_RECEIVED                               */
/*==============================================================*/

CREATE TABLE [BDVPIPESAGEM].[DUAOT_WEIGHING_RECEIVED](
	[DUAO_WEIGHING_RECEIVED_ID] [int] IDENTITY(1,1) NOT NULL,
	[DUAO_RECEIVED_STATUS] [varchar](5) NOT NULL,
	[DUAO_COMPANY] [varchar](100) NULL,
	[DUAO_MESSAGE_ID] [varchar](100) NOT NULL,
	[DUAO_FILE_NAME] [varchar](900) NOT NULL,
	[DUAO_COMPOSITION_ID] [varchar](80) NOT NULL,
	[DUAO_RECEIVED_DATETIME] [datetime] NOT NULL,
	[DUAO_PROCESSED_DATETIME] [datetime] NULL,
	[DUAO_PROCESSING_STATUS] [varchar](10) NOT NULL,
	[DUAO_WAGONS_INSERTED] [varchar](900) NULL,
	[DUAO_WAGONS_UPDATED] [varchar](900) NULL,
	[DUAO_EMPTY_WAGONS] [varchar](900) NULL,
	[DUAO_WAGONS_TOTAL] [int] NOT NULL,
	[DUAO_ADDITIONAL_INFO] [varchar](900) NULL,
 CONSTRAINT [PK_DUAO_WEIGHING_RECEIVED] PRIMARY KEY CLUSTERED 
(
	[DUAO_WEIGHING_RECEIVED_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


grant INSERT,DELETE,UPDATE on [BDVPIPESAGEM].[DUAOT_WEIGHING_RECEIVED] to AVPIPESAGEM
go

grant SELECT on [BDVPIPESAGEM].[DUAOT_WEIGHING_RECEIVED] to CVPIPESAGEM
go

CREATE NONCLUSTERED INDEX [DUAOT_01] ON [BDVPIPESAGEM].[DUAOT_WEIGHING_RECEIVED]
(
	[DUAO_COMPOSITION_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [DUAOT_02] ON [BDVPIPESAGEM].[DUAOT_WEIGHING_RECEIVED]
(
	[DUAO_PROCESSED_DATETIME] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [DUAOT_03] ON [BDVPIPESAGEM].[DUAOT_WEIGHING_RECEIVED]
(
	[DUAO_RECEIVED_DATETIME] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [DUAOT_04] ON [BDVPIPESAGEM].[DUAOT_WEIGHING_RECEIVED]
(
	[DUAO_MESSAGE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO